name: Lint Code & Run Tests & Trigger Netlify Deploy (CI)
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - '16.x'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run lint
  test-unit:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - '16.x'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run test-without-watcher
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -d '{}' https://api.netlify.com/build_hooks/62c2028a355a9e4f69111ab6
